language: objective-c
xcode_project: ILCommonKitDemo/ILCommonKitDemo.xcodeproj # path to your xcodeproj folder
xcode_scheme: ILCommonKitDemoTests
osx_image: xcode7
script: 
  - xctool -project ILCommonKitDemo/ILCommonKitDemo.xcodeproj -scheme ILCommonKitDemoTests build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
after_success:
  - bash <(curl -s https://codecov.io/bash)

