osx_image: xcode8
language: objective-c
xcode_project: ILCommonKitDemo/ILCommonKitDemo.xcodeproj # path to your xcodeproj folder
xcode_scheme: ILCommonKitDemoTests
osx_image: xcode8.2
#before_script:
#- brew update
#xcode_sdk: iphonesimulator10.2
script: 
  - xctool -project ILCommonKitDemo/ILCommonKitDemo.xcodeproj -scheme ILCommonKitDemoTests -sdk iphonesimulator10.2 build test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
after_success:
  - bash <(curl -s https://codecov.io/bash)

